#spring.application.name=e-learning
spring:
  application:
    name: e-learning

  data:
    mongodb:
      uri: mongodb://localhost:27017/e-learning

server:
  tomcat:
    relaxed-query-chars: >
      |,[,],{,}
  forward-headers-strategy: framework
stream:
  image: http://localhost:8080/image/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      uri: mongodb://seu:seu@e-learning:27017/
      authentication-database: admin
      database: e-learning